### ISSUE TITLE
Leaked activity retention

### ISSUE THREAD

**Issue by rpisu** [teads/TeadsSDK-android#88]
Hi, I have some troubles with leak references using in InReadTopAdView in a fragment.

The fragment is placed in an Activity AppBarLayout and it's injected programmatically.

Activity ui
```
    <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <include
            android:id="@+id/main_toolbar"
            layout="@layout/toolbar_layout" />

        <include
            android:id="@+id/main_ad_container"
            layout="@layout/ad_layout" />
    </android.support.design.widget.AppBarLayout>
```

fragment ui
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:teads="http://schemas.android.com/apk/res-auto"
    android:id="@+id/teads_container"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:background="@color/black">

    <tv.teads.sdk.publisher.InReadTopAdView
        android:id="@+id/teads_adview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        teads:teads_autoload="true" />

</LinearLayout>
```

I launch the adRequest in fragment's onViewCreated() (config.persistentView is false)
I notify the TeadsAd object with all callbacks (destroy / TeadsAd.clean(); , resume, pause) 

But if you enter/leave the activity (about 10~20 times) the app crashes with this stacktrace:

> 21 13:36:10.641 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.641 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.641 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.641 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.641 20566-22908/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 19: [select * from events where nextSending < ? AND maxSending > ?] unable to open database file
> 04-21 13:36:10.642 20566-22908/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file (code 14); query: select * from events where nextSending < ? AND maxSending > ?
> 04-21 13:36:10.643 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.643 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.643 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.644 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.644 20566-22908/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 34: [select * from events ORDER BY nextSending ASC LIMIT 1] unable to open database file
> 04-21 13:36:10.644 20566-22908/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file (code 14); query: select * from events ORDER BY nextSending ASC LIMIT 1
> 04-21 13:36:10.647 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.647 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.647 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.647 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.647 20566-22908/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 19: [select * from events where nextSending < ? AND maxSending > ?] unable to open database file
> 04-21 13:36:10.648 20566-22908/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file (code 14); query: select * from events where nextSending < ? AND maxSending > ?
> 04-21 13:36:10.680 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.680 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.681 20566-22908/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.681 20566-22908/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.681 20566-22908/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 34: [select * from events ORDER BY nextSending ASC LIMIT 1] unable to open database file
> 04-21 13:36:10.681 20566-22908/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file (code 14); query: select * from events ORDER BY nextSending ASC LIMIT 1
> 04-21 13:36:10.708 20566-20566/it.doveconviene.android E/TEADS VISIBILITY: false
> 04-21 13:36:10.724 20566-20667/it.doveconviene.android E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -2147483646
> 04-21 13:36:10.724 20566-20667/it.doveconviene.android E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
> 04-21 13:36:10.729 20566-20667/it.doveconviene.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
> 04-21 13:36:10.912 20566-22913/it.doveconviene.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
> 04-21 13:36:10.914 20566-22916/it.doveconviene.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
> 04-21 13:36:10.977 20566-22913/it.doveconviene.android E/NativeCrypto: AppData::create pipe(2) failed: Too many open files
> 04-21 13:36:10.991 20566-22913/it.doveconviene.android E/teads#EventService: sendCall failure: https://t.teads.tv/track?action=impression&vid=25e72e07667b5e1cd7d8e5647567be1f914662e9&gid=129286&cid=72208&pid=54934&be=1&impid=1&mediaFileType=[MEDIAFILETYPE]&auctid=854a22a2-0005-438a-8b1c-32bf4090c4a2 cause: Too many open files
> 04-21 13:36:10.993 20566-22913/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.993 20566-22913/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.993 20566-22913/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:10.993 20566-22913/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:10.993 20566-22913/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 21: [UPDATE events SET retryCount=?,creationDate=?,lastSending=?,nextSending=?,maxSending=?,url=? WHERE  _id=?] unable to open database file
> 04-21 13:36:11.029 20566-20566/it.doveconviene.android E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
> 04-21 13:36:11.037 20566-20566/it.doveconviene.android E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                          Process: it.doveconviene.android, PID: 20566
>                                                                          java.lang.OutOfMemoryError: Could not allocate JNI Env
>                                                                              at java.lang.Thread.nativeCreate(Native Method)
>                                                                              at java.lang.Thread.start(Thread.java:730)
>                                                                              at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
>                                                                              at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
>                                                                              at okhttp3.Dispatcher.enqueue(Dispatcher.java:112)
>                                                                              at okhttp3.RealCall.enqueue(RealCall.java:78)
>                                                                              at okhttp3.RealCall.enqueue(RealCall.java:70)
>                                                                              at tv.teads.network.okhttp.OkHttpNetworkCall.enqueue(OkHttpNetworkCall.java:30)
>                                                                              at tv.teads.adserver.AdServerClient.downloadAd(Unknown Source)
>                                                                              at tv.teads.adserver.AdServerClient.getAd(Unknown Source)
>                                                                              at tv.teads.sdk.publisher.BaseTeadsAd.a(BaseTeadsAd.java:223)
>                                                                              at tv.teads.sdk.publisher.BaseTeadsAd.onSlotAvailability(BaseTeadsAd.java:953)
>                                                                              at tv.teads.sdk.adContainer.InReadTopAdContainer.d(InReadTopAdContainer.java:152)
>                                                                              at tv.teads.sdk.publisher.BaseTeadsAd.load(BaseTeadsAd.java:362)
>                                                                              at it.doveconviene.android.ui.gridheader.teads.AHViewTeads.onViewCreated(AHViewTeads.java:64)
>                                                                              at it.doveconviene.android.ui.gridheader.AHFragment.onViewCreated(AHFragment.java:123)
>                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1265)
>                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1472)
>                                                                              at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1691)
>                                                                              at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3440)
>                                                                              at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
>                                                                              at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
>                                                                              at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
>                                                                              at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
>                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
>                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
>                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
>                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
>                                                                              at it.doveconviene.android.utils.ViewHelper.createView(ViewHelper.java:292)
>                                                                              at it.doveconviene.android.ui.base.fragment.UIFBaseGridFragment.setupHeader(UIFBaseGridFragment.java:419)
>                                                                              at it.doveconviene.android.ui.base.fragment.UIFBaseGridFragment.setupAdView(UIFBaseGridFragment.java:514)
>                                                                              at it.doveconviene.android.ui.base.fragment.UIFBaseGridFragment.onActivityCreated(UIFBaseGridFragment.java:191)
>                                                                              at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
>                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
>                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
>                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
>                                                                              at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
>                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
>                                                                              at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
>                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
>                                                                              at android.app.Activity.performStart(Activity.java:6681)
>                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
>                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
>                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
>                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                              at android.os.Looper.loop(Looper.java:154)
> 04-21 13:36:11.037 20566-20566/it.doveconviene.android E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6077)
>                                                                              at java.lang.reflect.Method.invoke(Native Method)
>                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
> 04-21 13:36:11.124 20566-20642/it.doveconviene.android E/SWRVE: RESTClient unable to connect to http://6013.eu-content.swrve.com/api/1/user_resources_and_campaigns?location_version=1&etag=cve-ig%3D%3D%3AMtGhbw%3D%3D%3AVoynbg%3D%3D&device_width=1440&joined=1492711218340&api_key=IIiLDoFhN0XNWnHDO6f&android_device_ydpi=492.606&user=7ee56643-e941-4c90-922a-f2b2e497dfd8&device_height=2392&device_dpi=560.0&app_version=4.8.0&app_store=google&version=6&device_name=motorola+Nexus+6&os_version=7.0&language=en-AU&orientation=both&conversation_version=4&android_device_xdpi=494.27
> 04-21 13:36:11.125 20566-20642/it.doveconviene.android E/SwrveSDK: Error downloading resources and campaigns
> 04-21 13:36:11.151 20566-22914/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.151 20566-22914/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.151 20566-22914/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.151 20566-22914/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.151 20566-22914/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 8: [DELETE FROM events WHERE  _id = ?] unable to open database file
> 04-21 13:36:11.221 20566-22916/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.222 20566-22916/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.222 20566-22916/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.222 20566-22916/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.222 20566-22916/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 8: [DELETE FROM events WHERE  _id = ?] unable to open database file
> 04-21 13:36:11.251 20566-22916/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.251 20566-22916/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.251 20566-22916/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
> 04-21 13:36:11.251 20566-22916/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32456: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 04-21 13:36:11.251 20566-22916/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 11: [DELETE FROM events WHERE maxSending < 1492774571250] unable to open database file
> 04-21 13:36:11.252 20566-22916/it.doveconviene.android E/CursorWindow: Could not allocate CursorWindow '/data/user/0/it.doveconviene.android/databases/teads' of size 2097152 due to error -24.
> 04-21 13:36:16.178 20566-20599/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30188 of [bda77dda96]
> 04-21 13:36:16.178 20566-20599/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30188: (24) open(/data/user/0/it.doveconviene.android/databases) - 
> 

Compiled mode: debug
Teads Version: 2.4.4
LeakCanary report:

![device-2017-04-21-095125](https://cloud.githubusercontent.com/assets/6348531/25272031/8c1a495c-2686-11e7-8313-fb86b3beab3a.png)

**Comment by HugoGresse** [comment]
Thanks for reporting it, we'll fix it and get back to you this week.

**Comment by HugoGresse** [comment]
This should be fixed in [v2.4.6 ](https://github.com/teads/TeadsSDK-android/releases/tag/v2.4.6)

Let me know if there is still the leak. In the meantime I'll close the issue.

Best,

**Comment by alexpopa95** [comment]
Hello @HugoGresse 
We still have the same bug after update v2.4.6

This is the complete log which seems the same as before, on **Huawei P9 Lite**:
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 15: [SELECT value FROM settings WHERE key = ?] unable to open database file
> 05-02 11:28:27.302 19744-19992/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files); query: SELECT value FROM settings WHERE key = ?
> 05-02 11:28:27.312 19744-19992/it.doveconviene.android E/DoveConviene/Plot: Unhandled exception in onPostExecute
>                                                                             android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files)
>                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
>                                                                                 at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
>                                                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
>                                                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>                                                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
>                                                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
>                                                                                 at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>                                                                                 at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.n(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.p(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.PlotBackgroundService$21.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.c.b$a$1.handleMessage(Unknown Source)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:135)
>                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 15: [SELECT value FROM settings WHERE key = ?] unable to open database file
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files); query: SELECT value FROM settings WHERE key = ?
> 05-02 11:28:27.322 19744-19992/it.doveconviene.android E/DoveConviene/Plot: Unhandled exception in onPostExecute
>                                                                             android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files)
>                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
>                                                                                 at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
>                                                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
>                                                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>                                                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
>                                                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
>                                                                                 at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>                                                                                 at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.n(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.p(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.PlotBackgroundService$21.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.c.b$a$1.handleMessage(Unknown Source)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:135)
>                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 15: [SELECT value FROM settings WHERE key = ?] unable to open database file
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files); query: SELECT value FROM settings WHERE key = ?
> 05-02 11:28:27.332 19744-19992/it.doveconviene.android E/DoveConviene/Plot: Unhandled exception in onPostExecute
>                                                                             android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files)
>                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
>                                                                                 at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
>                                                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
>                                                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>                                                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
>                                                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
>                                                                                 at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>                                                                                 at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.n(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.p(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.PlotBackgroundService$21.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.c.b$a$1.handleMessage(Unknown Source)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:135)
>                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 30078 of [9491ba7d73]
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:30078: (24) open(/data/data/it.doveconviene.android/databases/_plot-journal) - 
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteLog: (14) statement aborts at 15: [SELECT value FROM settings WHERE key = ?] unable to open database file
> 05-02 11:28:27.342 19744-19992/it.doveconviene.android E/SQLiteQuery: exception: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files); query: SELECT value FROM settings WHERE key = ?
> 05-02 11:28:27.352 19744-19992/it.doveconviene.android E/DoveConviene/Plot: Unhandled exception in onPostExecute
>                                                                             android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file(Sqlite code 14),(OS error - 24:Too many open files)
>                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
>                                                                                 at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
>                                                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
>                                                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>                                                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
>                                                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
>                                                                                 at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>                                                                                 at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.n(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.p(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.a.e.h.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.PlotBackgroundService$21.a(Unknown Source)
>                                                                                 at com.plotprojects.retail.android.internal.c.b$a$1.handleMessage(Unknown Source)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:135)
>                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)

This is the crash log on major **Samsung Devices**:

> 05-02 11:45:00.673 14475-17843/it.doveconviene.android E/Parcel: dup() failed in Parcel::read, i is 1, fds[i] is -1, fd_count is 2, error: Too many open files
> 05-02 11:45:00.674 14475-17843/it.doveconviene.android E/BufferQueueProducer: [SurfaceTexture-0-14475-20] dequeueBuffer: createGraphicBuffer failed
> 05-02 11:45:00.674 14475-17843/it.doveconviene.android E/ACodec: dequeueBuffer failed: BAD_VALUE(-22).
> 05-02 11:45:00.683 14475-17843/it.doveconviene.android E/BufferQueueProducer: [SurfaceTexture-0-14475-20] dequeueBuffer: createGraphicBuffer failed
> 05-02 11:45:00.684 14475-17843/it.doveconviene.android E/ACodec: dequeueBuffer failed: BAD_VALUE(-22).
> 05-02 11:45:00.684 14475-14888/it.doveconviene.android E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
> 05-02 11:45:00.686 14475-17843/it.doveconviene.android E/BufferQueueProducer: [SurfaceTexture-0-14475-20] dequeueBuffer: createGraphicBuffer failed
> 05-02 11:45:00.686 14475-17843/it.doveconviene.android E/ACodec: dequeueBuffer failed: BAD_VALUE(-22).
> 05-02 11:45:00.705 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.787 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.803 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.819 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.835 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.852 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.868 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.885 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131074) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131072) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.897 14475-17857/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.898 14475-17857/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.898 14475-17857/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.898 14475-17857/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.898 14475-17857/it.doveconviene.android E/SQLiteLog: (2062) statement aborts at 8: [DELETE FROM events WHERE  _id = ?] unable to open database file
> 05-02 11:45:00.905 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.
> 05-02 11:45:00.905 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131072) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.905 14475-17855/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.905 14475-17855/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131074) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131072) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.906 14475-17855/it.doveconviene.android E/SQLiteLog: (2062) statement aborts at 8: [DELETE FROM events WHERE  _id = ?] unable to open database file
> 05-02 11:45:00.907 14475-17843/it.doveconviene.android E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
> 05-02 11:45:00.908 14475-17843/it.doveconviene.android E/SurfaceTexture: thread attach failed: 0xffffffff
> 05-02 11:45:00.908 14475-17843/it.doveconviene.android W/SurfaceTexture: onFrameAvailable event will not posted
> 05-02 11:45:00.909 14475-17843/it.doveconviene.android E/BufferQueueProducer: [SurfaceTexture-0-14475-20] dequeueBuffer: createGraphicBuffer failed
> 05-02 11:45:00.909 14475-17843/it.doveconviene.android E/ACodec: dequeueBuffer failed: BAD_VALUE(-22).
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131072) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131074) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android W/SQLiteLog: (28) failed to open "/data/user/0/it.doveconviene.android/databases/teads-journal" with flag (131072) and mode_t (1b0) due to error (24)
> 05-02 11:45:00.910 14475-17855/it.doveconviene.android E/SQLiteLog: (14) cannot open file at line 32763 of [bda77dda96]
> 05-02 11:45:00.911 14475-17855/it.doveconviene.android E/SQLiteLog: (14) os_unix.c:32763: (24) open(/data/user/0/it.doveconviene.android/databases/teads-journal) - 
> 05-02 11:45:00.911 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Process  : Pid (14475) Uid (10209) Euid (10209) Gid (10209) Egid (10209)
> 05-02 11:45:00.911 14475-17855/it.doveconviene.android E/SQLiteLog: (1) Stat of /data/user/0/it.doveconviene.android/databases/teads-journal : st_ino(591924)
> 05-02 11:45:00.911 14475-17855/it.doveconviene.android E/SQLiteLog: (1) st_mode (100660) st_uid (10209) st_gid (10209)
> 05-02 11:45:00.911 14475-17855/it.doveconviene.android E/SQLiteLog: (2062) statement aborts at 11: [DELETE FROM events WHERE maxSending < 1493718300909] unable to open database file
> 05-02 11:45:00.914 14475-17855/it.doveconviene.android E/CursorWindow: Could not allocate CursorWindow '/data/user/0/it.doveconviene.android/databases/teads' of size 2097152 due to error -24.
> 05-02 11:45:00.919 14475-14475/it.doveconviene.android E/ViewRootImpl@6147726[FlyersCategoryActivity]: ViewRootImpl #2 Surface is not valid.

After some research I found [this GitHub issue for ExoPlayer](https://github.com/google/ExoPlayer/issues/1066). I hope this helps

Thanks.

**Comment by HugoGresse** [comment]
Thanks for the additional information @alexpopa95
Reading the crash log, it didn't seems to be related in anyway with ExoPlayer but our SQLite management within the SDK. To be more clear, we open and close the DB connection each time we need to send a tracking event. Are you able to reproduce the issue in a standalone app?

**Comment by rpisu** [comment]
Yes, I reproduced the bug in your sample app.
Switch from "Inread Top scrollview" screen to "inread top listview" screen... until the app will crash

https://drive.google.com/file/d/0B03tHz5w8L_makRRZjNicFJ1WTg/view?usp=sharing

**Comment by HugoGresse** [comment]
Thanks but it does not seems to be related to the same issue.

**Comment by rpisu** [comment]
Hi, @HugoGresse. Thanks for supporting us.
 
I attach the  Teads SDK Demo crash logcat
https://pastebin.com/zGqMGMry

There are a lot of:

`05-02 15:25:35.974 20403-25358/tv.teads.teadssdkdemo E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]`

and

```
05-02 15:25:01.071 20403-24396/tv.teads.teadssdkdemo E/SQLiteQuery: exception: unable to open database file (code 14); query: select * from events ORDER BY nextSending ASC LIMIT 1
05-02 15:25:35.970 20403-25358/tv.teads.teadssdkdemo E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
```

which are similar to our issue.

**Comment by HugoGresse** [comment]
I've updated the develop branch which should reduce the issue by using the `onStop` rather than `onDestroy`. In the meantime we will work on a new version that definitively fix SQL connection issue.

**Comment by benjaminvolland** [comment]
Hi @rpisu and @alexpopa95, we have released a new version, the 2.4.9, which fix this SQL connection issue: [here](https://github.com/teads/TeadsSDK-android/releases/tag/v2.4.9)

Also in this version to avoid the activity leaks, you don't need to give an `Activity` to the TeadsAd builder, a `Context` is enough, I recommend you to give the `ApplicationContext`. 

Contrary to that @HugoGresse said, don't clean the TeadsAd instance in the `onStop`(otherwise it will destroy the ad when the user click to go in full screen, thanks the QA to found this issue ^^), do it in the `onDestroy` as in the sample.

**Comment by rpisu** [comment]
Hi @benjaminvolland  

Yes, we keeped the TeadsAd clean() in onDestroy. 

Thank you for the new version! we appreciate it a lot

**Comment by benjaminvolland** [comment]
Hi @rpisu and @alexpopa95, I forgot to said you that for enable the fix on the SQL connection issue you have to disable the event retention in your TeadsConfiguration object: `mTeadsConfiguration.disableEventRetention = true;`
Sorry for the memory lapse

**Comment by rpisu** [comment]
Hi @benjaminvolland, no problem! We already spotted the new configuration. 
We can't reproduce the leak now, so I suppose that all is ok. thanks!
